Default: &defaults
  database: dossier.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: dossier_test.sqlite3
  <<: *defaults

Staging:
  database: dossier_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: dossier_production.sqlite3
  poolsize: 100
  <<: *defaults
